package com.mrredhood.nexus.core.workspace

import android.util.Base64
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder
import java.security.MessageDigest

data class GitHubRemoteFile(val path: String, val sha: String, val size: Long = 0L)
data class GitHubSyncStatus(val branch: String, val remoteCommit: String, val changed: List<String>, val added: List<String>, val deleted: List<String>, val unchanged: Int)
data class GitHubCommitResult(val commitSha: String, val treeSha: String, val message: String)
data class GitBranch(val name: String, val sha: String, val current: Boolean)
data class GitCommit(val sha: String, val message: String, val author: String, val timestamp: String, val filesChanged: Int)
data class GitDiff(val path: String, val before: String, val after: String, val addedLines: Int, val removedLines: Int)
data class GitHubRepository(val fullName: String, val defaultBranch: String, val private: Boolean, val description: String?)
data class GitHubWorkflow(val id: Long, val name: String, val path: String, val state: String, val url: String?)
data class GitHubWorkflowRun(val id: Long, val name: String, val status: String, val conclusion: String?, val branch: String, val sha: String, val createdAt: String, val updatedAt: String, val htmlUrl: String?)
data class GitHubArtifact(val id: Long, val name: String, val sizeBytes: Long, val expired: Boolean, val createdAt: String, val expiresAt: String?, val downloadUrl: String?)

class GitHubRepositoryService(private val fileSystem: WorkspaceFileSystem) {
    suspend fun status(repository:String,branch:String,token:String,workspace:Workspace)=withContext(Dispatchers.IO){val remote=loadRemoteTree(repository,branch,token);val local=collectLocalFiles(workspace);val comparable=remote.files.filterKeys{it in remote.contents};val changed=mutableListOf<String>();val added=mutableListOf<String>();local.forEach{(p,c)->val r=comparable[p];if(r==null)added+=p else if(gitBlobSha(c)!=r.sha)changed+=p};val deleted=comparable.keys.filter{it !in local.keys}.sorted();val unchanged=local.count{(p,c)->comparable[p]?.sha==gitBlobSha(c)};GitHubSyncStatus(branch,remote.commitSha,changed.sorted(),added.sorted(),deleted,unchanged)}
    suspend fun fetch(repository:String,branch:String,token:String,workspace:Workspace)=withContext(Dispatchers.IO){val remote=loadRemoteTree(repository,branch,token);var count=0;remote.contents.keys.sorted().forEach{p->fileSystem.write(workspace,p,remote.contents.getValue(p),mimeTypeFor(p));count++};count}
    suspend fun diff(repository:String,branch:String,token:String,workspace:Workspace)=withContext(Dispatchers.IO){val remote=loadRemoteTree(repository,branch,token);val local=collectLocalFiles(workspace);val out=mutableListOf<GitDiff>();(local.keys+remote.contents.keys).distinct().sorted().forEach{p->val before=remote.contents[p].orEmpty();val after=local[p].orEmpty();if(before!=after){val(a,r)=lineStats(before,after);out+=GitDiff(p,before,after,a,r)}};out}
    suspend fun commitAndPush(repository:String,branch:String,token:String,workspace:Workspace,message:String,staged:Set<String>?=null)=withContext(Dispatchers.IO){require(message.isNotBlank()){ "Commit message is required" };val remote=loadRemoteTree(repository,branch,token);val local=collectLocalFiles(workspace);val allowed=staged ?: (local.keys+remote.contents.keys).toSet();val entries=mutableListOf<JSONObject>();allowed.sorted().forEach{p->if(p.startsWith(".git/"))return@forEach;val content=local[p];if(content!=null)entries+=JSONObject().apply{put("path",p);put("mode","100644");put("type","blob");put("content",content)}else if(remote.files.containsKey(p))entries+=JSONObject().apply{put("path",p);put("mode","100644");put("type","blob");put("sha",JSONObject.NULL)}};(remote.files.keys-allowed).forEach{p->entries+=JSONObject().apply{put("path",p);put("mode","100644");put("type","blob");put("sha",remote.files.getValue(p).sha)}};val tree=apiPost("/repos/$repository/git/trees",token,JSONObject().apply{put("base_tree",remote.treeSha);put("tree",JSONArray(entries))});val treeSha=tree.getString("sha");val commit=apiPost("/repos/$repository/git/commits",token,JSONObject().apply{put("message",message.trim());put("tree",treeSha);put("parents",JSONArray().put(remote.commitSha))});val commitSha=commit.getString("sha");apiPatch("/repos/$repository/git/refs/heads/${encode(branch)}",token,JSONObject().put("sha",commitSha));GitHubCommitResult(commitSha,treeSha,message.trim())}
    suspend fun repositories(token:String,query:String?=null,limit:Int=50)=withContext(Dispatchers.IO){val path=if(query.isNullOrBlank())"/user/repos?sort=updated&per_page=${limit.coerceIn(1,100)}" else "/search/repositories?q=${encode(query)}&per_page=${limit.coerceIn(1,100)}";val root=apiGet(path,token);val arr=if(root.has("items"))root.getJSONArray("items") else root as JSONArray;parseRepositories(arr)}
    suspend fun repository(repository:String,token:String)=withContext(Dispatchers.IO){parseRepository(apiGet("/repos/$repository",token))}
    suspend fun branches(repository:String,current:String,token:String)=withContext(Dispatchers.IO){val arr=apiGetArray("/repos/$repository/branches?per_page=100",token);(0 until arr.length()).map{i->val o=arr.getJSONObject(i);GitBranch(o.getString("name"),o.getJSONObject("commit").getString("sha"),o.getString("name")==current)}.sortedBy{it.name}}
    suspend fun createBranch(repository:String,name:String,fromSha:String,token:String)=withContext(Dispatchers.IO){require(name.matches(Regex("[A-Za-z0-9._/-]+"))){"Invalid branch name"};apiPost("/repos/$repository/git/refs",token,JSONObject().apply{put("ref","refs/heads/$name");put("sha",fromSha)})}
    suspend fun checkout(repository:String,branch:String,token:String)=withContext(Dispatchers.IO){apiGet("/repos/$repository/git/ref/heads/${encode(branch)}",token).getJSONObject("object").getString("sha")}
    suspend fun log(repository:String,branch:String,token:String,limit:Int=30)=withContext(Dispatchers.IO){val arr=apiGetArray("/repos/$repository/commits?sha=${encode(branch)}&per_page=${limit.coerceIn(1,100)}",token);(0 until arr.length()).map{i->val o=arr.getJSONObject(i);val c=o.getJSONObject("commit");val a=c.optJSONObject("author");val stats=o.optJSONObject("stats");GitCommit(o.getString("sha"),c.getString("message").lineSequence().first(),a?.optString("name","Unknown")?:"Unknown",a?.optString("date","")?:"",stats?.optInt("total",0)?:0)}}
    suspend fun workflows(repository:String,token:String)=withContext(Dispatchers.IO){val arr=apiGet("/repos/$repository/actions/workflows?per_page=100").getJSONArray("workflows");(0 until arr.length()).map{i->val o=arr.getJSONObject(i);GitHubWorkflow(o.getLong("id"),o.getString("name"),o.getString("path"),o.getString("state"),o.optString("html_url").ifBlank{null})}}
    suspend fun workflowRuns(repository:String,token:String,workflowId:Long?=null,branch:String?=null,limit:Int=30)=withContext(Dispatchers.IO){val path=buildString{append("/repos/$repository/actions/");if(workflowId!=null)append("workflows/$workflowId/") else append("");append("runs?per_page=${limit.coerceIn(1,100)}");if(!branch.isNullOrBlank())append("&branch=${encode(branch)}")};val arr=apiGet(path,token).getJSONArray("workflow_runs");(0 until arr.length()).map{i->val o=arr.getJSONObject(i);GitHubWorkflowRun(o.getLong("id"),o.optString("name","Workflow"),o.optString("status"),o.optString("conclusion").ifBlank{null},o.optString("head_branch"),o.optString("head_sha"),o.optString("created_at"),o.optString("updated_at"),o.optString("html_url").ifBlank{null})}}
    suspend fun dispatchWorkflow(repository:String,workflowId:Long,token:String,branch:String="main",inputs:Map<String,String>=emptyMap())=withContext(Dispatchers.IO){val body=JSONObject().apply{put("ref",branch);if(inputs.isNotEmpty())put("inputs",JSONObject(inputs))};apiPost("/repos/$repository/actions/workflows/$workflowId/dispatches",token,body);Unit}
    suspend fun workflowRun(repository:String,runId:Long,token:String)=withContext(Dispatchers.IO){val o=apiGet("/repos/$repository/actions/runs/$runId",token);GitHubWorkflowRun(o.getLong("id"),o.optString("name","Workflow"),o.optString("status"),o.optString("conclusion").ifBlank{null},o.optString("head_branch"),o.optString("head_sha"),o.optString("created_at"),o.optString("updated_at"),o.optString("html_url").ifBlank{null})}
    suspend fun artifacts(repository:String,token:String,runId:Long?=null,limit:Int=50)=withContext(Dispatchers.IO){val path=if(runId==null)"/repos/$repository/actions/artifacts?per_page=${limit.coerceIn(1,100)}" else "/repos/$repository/actions/runs/$runId/artifacts?per_page=${limit.coerceIn(1,100)}";val arr=apiGet(path).getJSONArray("artifacts");(0 until arr.length()).map{i->val o=arr.getJSONObject(i);GitHubArtifact(o.getLong("id"),o.getString("name"),o.optLong("size_in_bytes",0),o.optBoolean("expired",false),o.optString("created_at"),o.optString("expires_at").ifBlank{null},o.optString("archive_download_url").ifBlank{null})}}
    private fun parseRepositories(arr:JSONArray):List<GitHubRepository>=(0 until arr.length()).map{parseRepository(arr.getJSONObject(it))}
    private fun parseRepository(o:JSONObject)=GitHubRepository(o.getString("full_name"),o.optString("default_branch","main"),o.optBoolean("private",false),o.optString("description").ifBlank{null})
    private suspend fun loadRemoteTree(repository:String,branch:String,token:String):RemoteTree{val ref=apiGet("/repos/$repository/git/ref/heads/${encode(branch)}",token);val commitSha=ref.getJSONObject("object").getString("sha");val commit=apiGet("/repos/$repository/git/commits/$commitSha",token);val treeSha=commit.getJSONObject("tree").getString("sha");val tree=apiGet("/repos/$repository/git/trees/$treeSha?recursive=1",token);val files=linkedMapOf<String,GitHubRemoteFile>();val contents=linkedMapOf<String,String>();val items=tree.optJSONArray("tree")?:JSONArray();for(i in 0 until items.length()){val item=items.getJSONObject(i);if(item.optString("type")!="blob")continue;val p=item.getString("path");if(p.startsWith(".git/"))continue;val sha=item.getString("sha");val size=item.optLong("size",0);files[p]=GitHubRemoteFile(p,sha,size);if(size<=WorkspaceFileSystem.MAX_EDITABLE_FILE_BYTES){val blob=apiGet("/repos/$repository/git/blobs/$sha",token);if(blob.optString("encoding")=="base64"){val bytes=Base64.decode(blob.getString("content").replace("\n",""),Base64.DEFAULT);val text=bytes.toString(Charsets.UTF_8);if(text.toByteArray(Charsets.UTF_8).contentEquals(bytes))contents[p]=text}}};return RemoteTree(commitSha,treeSha,files,contents)}
    private suspend fun collectLocalFiles(workspace:Workspace):Map<String,String>{val result=linkedMapOf<String,String>();suspend fun visit(dir:String){fileSystem.list(workspace,dir).forEach{e->if(e.name==".git")return@forEach;if(e.type==EntryType.DIRECTORY)visit(e.relativePath)else if(e.sizeBytes<=WorkspaceFileSystem.MAX_EDITABLE_FILE_BYTES)runCatching{fileSystem.read(workspace,e.relativePath).content}.onSuccess{result[e.relativePath]=it}}};visit("");return result}
    private fun gitBlobSha(content:String):String{val b=content.toByteArray(Charsets.UTF_8);val h="blob ${b.size}\u0000".toByteArray(Charsets.UTF_8);return MessageDigest.getInstance("SHA-1").digest(h+b).joinToString(""){ "%02x".format(it) }}
    private fun lineStats(before:String,after:String):Pair<Int,Int>{val a=before.lines();val b=after.lines();var add=0;var rem=0;val n=maxOf(a.size,b.size);for(i in 0 until n){val x=a.getOrNull(i);val y=b.getOrNull(i);if(x!=y){if(y!=null)add++;if(x!=null)rem++}};return add to rem}
    private fun apiGet(path:String,token:String)=request("GET",path,token,null)
    private fun apiGetArray(path:String,token:String)=JSONArray(requestText("GET",path,token,null))
    private fun apiPost(path:String,token:String,body:JSONObject)=request("POST",path,token,body)
    private fun apiPatch(path:String,token:String,body:JSONObject)=request("PATCH",path,token,body)
    private fun request(method:String,path:String,token:String,body:JSONObject?):JSONObject{val response=requestText(method,path,token,body);return JSONObject(response)}
    private fun requestText(method:String,path:String,token:String,body:JSONObject?):String{require(token.isNotBlank()){ "GitHub token is not configured. Add it in Settings > GitHub." };val c=(URL("https://api.github.com$path").openConnection() as HttpURLConnection).apply{requestMethod=method;connectTimeout=15000;readTimeout=30000;setRequestProperty("Accept","application/vnd.github+json");setRequestProperty("Authorization","Bearer $token");setRequestProperty("X-GitHub-Api-Version","2022-11-28");setRequestProperty("User-Agent","Nexus-Android");if(body!=null){doOutput=true;setRequestProperty("Content-Type","application/json; charset=utf-8")}};body?.toString()?.toByteArray(Charsets.UTF_8)?.let{c.outputStream.use{s->s.write(it)}};val status=c.responseCode;val stream=if(status in 200..299)c.inputStream else c.errorStream;val response=stream?.bufferedReader()?.use{it.readText()}.orEmpty();c.disconnect();if(status !in 200..299){val m=runCatching{JSONObject(response).optString("message")}.getOrNull().orEmpty();error("GitHub API $status${if(m.isNotBlank())": $m" else ""}")};return response}
    private fun encode(v:String)=URLEncoder.encode(v,Charsets.UTF_8.name()).replace("+","%20")
    private fun mimeTypeFor(path:String)=when(path.substringAfterLast('.',"").lowercase()){ "json"->"application/json";"xml"->"application/xml";"html","htm"->"text/html";"css"->"text/css";else->"text/plain" }
    private data class RemoteTree(val commitSha:String,val treeSha:String,val files:Map<String,GitHubRemoteFile>,val contents:Map<String,String>)
}
